# Supabase Configuration
SUPABASE_URL = "https://mvsmfyobnhqhkspmjeaw.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12c21meW9ibmhxaGtzcG1qZWF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1MTkzMzgsImV4cCI6MjA3ODA5NTMzOH0.-5sZxtsvKRUpWPz0K7tUdKobD7-xiNW2z46-LKJLoRU"

# Backend API URL
BACKEND_API_URL = "http://localhost:8000"
